name: Django Tests

on:
    push:
        branches: 
            [main]
    pull_request:
        branches: 
            [main]
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set Up golang 1.2
              uses: actions/setup-go@v2
              with:
                    go-version: 1.12
            # - name: Install dependencies
            #   run: |
            #     go get -d -v ./... # Download dependencies without installing
            #     modules=$(go list -m all | awk '{if ($1 == "all") {print $2} else {print $1}}' | sort -u)
            #     go get -v $modules  # Install only the dependencies used in the project
            - name: Run tests
              run: |
                go test -v ./...


