name: Django Tests

on:
    push:
        branches: 
            [main]
    pull_request:
        branches: 
            [main]
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set Up golang 1.2
              uses: actions/setup-go@v2
              with:
                    go-version: 1.12
            - name: Install dependencies
              run: |
                go mod download
            - name: verify mod
              run: |
                go mod verify
            - name: tidy all
              run: |
                go mod tidy

            - name: Run tests
              run: |
                go test -v ./...


